name: Build and deploy angular app to GitHub Pages

on:
  push:
    branches:
    - main
    
jobs:
  deploy:
    defaults:
      run:
        working-directory: ./my-angular-app
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build-ghpages

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: pwd2
      run: pwd

    - name: ls2
      run: ls

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'wwwroot'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4