name: Testing Stuff

on:
  workflow_dispatch:
    inputs:
      SemVer:
        description: 'Semantic Version of the release'
        required: true

env:
  #these should match the output of the electron build
  WIN_FILENAME: my-angular-app Setup ${{ github.event.inputs.SemVer }}.exe
  WIN-P_FILENAME: my-angular-app ${{ github.event.inputs.SemVer }}.exe
  LIN_FILENAME: my-angular-app-${{ github.event.inputs.SemVer }}.AppImage
  MAC_FILENAME: my-angular-app-${{ github.event.inputs.SemVer }}-arm64.dmg

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: echo "Build of ${{ env.MAC_FILENAME }} successful"

    - name: Add annotation
      run: echo "::notice file=build.txt::Build completed successfully, view your site at https://example.com"
  other-job:
    runs-on: ubuntu-latest
    environment:
      name: release-url
      url: https://github.com/Josh-TX/basic-site/releases/tag/v1.0.0
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: echo "Build of ${{ env.WIN_FILENAME }} success"