name: Append-release

on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    steps:
    - name: Upload index.html
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/Josh-TX/basic-site/releases/155794594/assets
        asset_name: readme.txt
        asset_path: README.md
        asset_content_type: text/plain