name: build and publish docker

on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: joshtxdev/basic-site
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        platforms: linux/amd64,linux/arm64
        tags: latest,0.1.9