name: Release Electron

on:
  workflow_dispatch:
    inputs:
      SemVer:
        description: 'should be semantic versioning'
        required: true

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Validate Semantic Version
      run: |
        echo "Checking version format..."
        node validate-version.js ${{ github.event.inputs.SemVer }}

    - name: Install dependencies
      run: npm install
      working-directory: ./my-angular-app

    - name: Build Angular
      run: npm run build-ghpages
      working-directory: ./my-angular-app

    - name: Publish Electron
      run: npm run publish-electron
      working-directory: ./my-angular-app

    - name: Echo out
      run: dir
      working-directory: ./my-angular-app/out

    - name: create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: release v${{ github.event.inputs.SemVer }}
        tag_name: v${{ github.event.inputs.SemVer }}
        body_path: CHANGELOG.md

    - name: Upload index.html
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: my-angular-app v${{ github.event.inputs.SemVer }}.exe
        asset_path: my-angular-app/out/my-angular-app 0.0.0.exe
        asset_content_type: text/html