name: Release

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'The tag name'
        required: true
        default: 'myTagName'
      releaseName:
        description: 'The tag name'
        required: true
        default: 'myTagName'
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./my-angular-app

    - name: Build
      run: npm run build-ghpages
      working-directory: ./my-angular-app

    - name: create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.event.inputs.releaseName }}
        tag_name: ${{ github.event.inputs.tagName }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}


    - name: Upload index.html
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: my-index.html
        asset_path: my-angular-app/dist/browser/index.html
        asset_content_type: text/html